// product constants

// 产品列表请求动作
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST"
// 产品列表请求成功动作
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
// 产品列表请求失败
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL"

/**
 * 商品详情相关
 */
// 请求商品详情
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
// 商品详情请求成功动作
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
// 商品详情请求失败动作
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'


// 商品创建审查相关
export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";
